"""Corrigiendo resultado_quiz_tres

Revision ID: 1a42f152e418
Revises: 
Create Date: 2025-03-10 22:28:34.452781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a42f152e418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultado_quiz_tres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filantropo', sa.Float(), nullable=False),
    sa.Column('socializador', sa.Float(), nullable=False),
    sa.Column('triunfador', sa.Float(), nullable=False),
    sa.Column('jugador', sa.Float(), nullable=False),
    sa.Column('espiritu_libre', sa.Float(), nullable=False),
    sa.Column('disruptor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_quiz_tres')
    # ### end Alembic commands ###
