"""add institucion to user

Revision ID: 624fdffbc687
Revises: a4c8e07eef5b
Create Date: 2025-10-21 01:09:19.118062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624fdffbc687'
down_revision = 'a4c8e07eef5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institucion', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('institucion')

    # ### end Alembic commands ###
