"""modelo ADAT2

Revision ID: 730841e99f96
Revises: 47aa31b45061
Create Date: 2025-03-11 17:21:55.692925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730841e99f96'
down_revision = '47aa31b45061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuestas_correctas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('respuestas_incorrectas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_quiz', schema=None) as batch_op:
        batch_op.drop_column('respuestas_incorrectas')
        batch_op.drop_column('respuestas_correctas')

    # ### end Alembic commands ###
