"""empty message

Revision ID: 7c8b40a3c2e1
Revises: aa168da912bc
Create Date: 2025-03-11 12:40:54.721048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8b40a3c2e1'
down_revision = 'aa168da912bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultado_quiz_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensorial_intuitivo', sa.JSON(), nullable=False),
    sa.Column('visual_verbal', sa.JSON(), nullable=False),
    sa.Column('activo_reflexivo', sa.JSON(), nullable=False),
    sa.Column('secuencial_global', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_quiz_dos')
    # ### end Alembic commands ###
