"""modelo con nivel

Revision ID: 81009aa083fa
Revises: 5bec33977e19
Create Date: 2025-03-12 11:35:24.890774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81009aa083fa'
down_revision = '5bec33977e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('nivel_por_grados',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nivel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nivel_por_grados')
    op.drop_table('nivel')
    # ### end Alembic commands ###
