"""init clean

Revision ID: 84ab141315f5
Revises: 
Create Date: 2025-10-25 15:24:39.388152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ab141315f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=5000), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=100), nullable=False),
    sa.Column('option_b', sa.String(length=100), nullable=False),
    sa.Column('option_c', sa.String(length=100), nullable=False),
    sa.Column('option_d', sa.String(length=100), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_cuatro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=1000), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=3000), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=3000), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('option_e', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=True),
    sa.Column('nivel_grados_id', sa.Integer(), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('anios_experiencia', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegio.id'], ),
    sa.ForeignKeyConstraint(['nivel_grados_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actividad_generada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre_profesor', sa.String(length=200), nullable=False),
    sa.Column('grado', sa.String(length=50), nullable=False),
    sa.Column('asignatura', sa.String(length=200), nullable=False),
    sa.Column('tematica', sa.String(length=500), nullable=False),
    sa.Column('cantidad_estudiantes', sa.Integer(), nullable=False),
    sa.Column('tipo_actividad', sa.String(length=50), nullable=False),
    sa.Column('tiempo', sa.Integer(), nullable=False),
    sa.Column('recursos', sa.String(length=1000), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grados_dictados',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'grado_id'),
    info={'bind_key': None}
    )
    op.create_table('nivel_por_grados',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nivel_id'),
    info={'bind_key': None}
    )
    op.create_table('resultado_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abstraccion', sa.Float(), nullable=False),
    sa.Column('descomposicion', sa.Float(), nullable=False),
    sa.Column('pensamiento_algoritmico', sa.Float(), nullable=False),
    sa.Column('respuestas_correctas', sa.Integer(), nullable=False),
    sa.Column('respuestas_incorrectas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('resultado_quiz_cuatro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abstraccion', sa.Float(), nullable=False),
    sa.Column('descomposicion', sa.Float(), nullable=False),
    sa.Column('pensamiento_algoritmico', sa.Float(), nullable=False),
    sa.Column('respuestas_correctas', sa.Integer(), nullable=False),
    sa.Column('respuestas_incorrectas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('resultado_quiz_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensorial_intuitivo', sa.JSON(), nullable=False),
    sa.Column('visual_verbal', sa.JSON(), nullable=False),
    sa.Column('activo_reflexivo', sa.JSON(), nullable=False),
    sa.Column('secuencial_global', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('resultado_quiz_tres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filantropo', sa.Float(), nullable=False),
    sa.Column('socializador', sa.Float(), nullable=False),
    sa.Column('triunfador', sa.Float(), nullable=False),
    sa.Column('jugador', sa.Float(), nullable=False),
    sa.Column('espiritu_libre', sa.Float(), nullable=False),
    sa.Column('disruptor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('usuarios_cursos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'curso_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_cursos')
    op.drop_table('resultado_quiz_tres')
    op.drop_table('resultado_quiz_dos')
    op.drop_table('resultado_quiz_cuatro')
    op.drop_table('resultado_quiz')
    op.drop_table('nivel_por_grados')
    op.drop_table('grados_dictados')
    op.drop_table('answer')
    op.drop_table('actividad_generada')
    op.drop_table('user')
    op.drop_table('question_tres')
    op.drop_table('question_dos')
    op.drop_table('question_cuatro')
    op.drop_table('question')
    op.drop_table('nivel')
    op.drop_table('grado')
    op.drop_table('curso')
    op.drop_table('configuracion_sistema')
    op.drop_table('colegio')
    # ### end Alembic commands ###
