"""modelo con cursos2

Revision ID: a0b2ce5f7e9d
Revises: a16651c00f92
Create Date: 2025-03-11 23:06:20.539177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b2ce5f7e9d'
down_revision = 'a16651c00f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios_cursos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'curso_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=100), nullable=False, server_default="docente"))
        batch_op.drop_column('colegio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colegio', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('rol')

    op.drop_table('usuarios_cursos')
    op.drop_table('curso')
    # ### end Alembic commands ###
