"""modelo con colegios

Revision ID: a16651c00f92
Revises: 730841e99f96
Create Date: 2025-03-11 22:29:35.536298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16651c00f92'
down_revision = '730841e99f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colegio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'colegio', ['colegio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('colegio_id')

    op.drop_table('colegio')
    # ### end Alembic commands ###
