"""Corrigiendo resultado_quiz_dos

Revision ID: aa168da912bc
Revises: c1dc0f2592ff
Create Date: 2025-03-11 12:24:53.984005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa168da912bc'
down_revision = 'c1dc0f2592ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_quiz_dos', schema=None) as batch_op:
        batch_op.alter_column('sensorial_intuitivo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('visual_verbal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('activo_reflexivo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('secuencial_global',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado_quiz_dos', schema=None) as batch_op:
        batch_op.alter_column('secuencial_global',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('activo_reflexivo',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('visual_verbal',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('sensorial_intuitivo',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
