"""Corrigiendo resultado_quiz_tres

Revision ID: c1dc0f2592ff
Revises: 1a42f152e418
Create Date: 2025-03-11 11:54:13.249919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dc0f2592ff'
down_revision = '1a42f152e418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultado_quiz_dos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensorial_intuitivo', sa.Float(), nullable=False),
    sa.Column('visual_verbal', sa.Float(), nullable=False),
    sa.Column('activo_reflexivo', sa.Float(), nullable=False),
    sa.Column('secuencial_global', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_quiz_dos')
    # ### end Alembic commands ###
