"""modelo final

Revision ID: c76fab175d4a
Revises: baef56edbf7b
Create Date: 2025-03-12 12:27:39.429704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76fab175d4a'
down_revision = 'baef56edbf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grados_dictados',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'grado_id')
    )
    op.drop_table('usuarios_cursos_grados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_cursos_grados',
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('curso_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], name='usuarios_cursos_grados_curso_id_fkey'),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], name='usuarios_cursos_grados_grado_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='usuarios_cursos_grados_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('usuario_id', 'curso_id', 'grado_id', name='usuarios_cursos_grados_pkey')
    )
    op.drop_table('grados_dictados')
    # ### end Alembic commands ###
