version: '3.8'

services:
  web:
    build: .
    container_name: adat_app
    ports:
      - "80:5002"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=mi_secreto
    volumes:
      - .:/app
      - ./instance:/app/instance
    restart: unless-stopped
    networks:
      - adat_network

networks:
  adat_network:
    driver: bridge
